spring.application.name=observatorio

# Banco de dados (preencha com suas credenciais)
spring.datasource.url=jdbc:postgresql://db.SEU_PROJETO.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Servidor
server.port=8080